version: '3'
services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - ./create-database.sh:/docker-entrypoint-initdb.d/create-database.sh
    ports:
      - 5432:5432
    restart: unless-stopped
  java-birds-service:
    image: bondariksania/birds:v2
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres_db
